### ISSUE TITLE
Errore sui numeri del grafico

### ISSUE THREAD

**Issue by tonyiovino** [DarkFighterLuke/covidgraphs#1]
Errore nei dati dei grafici provinciali.

Esempio: grafico della provincia Caserta e Salerno.

**Comment by tonyiovino** [comment]
Grafico di Caserta:

![20201110_115615.jpg](https://user-images.githubusercontent.com/49679221/98532966-a8527080-2282-11eb-9e76-84d02112a965.jpg)

Grafico di Salerno:

![20201110_115640.jpg](https://user-images.githubusercontent.com/49679221/98533163-e8b1ee80-2282-11eb-8019-d7680b9aae4f.jpg)

**Comment by DarkFighterLuke** [comment]
Fixed with commit 8acf0bca0433aa9cdcf8c67ce31b1b961b236b11
